name: sun19-enterthepolygon

services:
  db:
    image: postgres:10.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 512

  web:
    build: .
    restart: unless-stopped
    command: gunicorn exif.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_data:/usr/src/exif/media
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DEFAULT_USER=pontifex
      - DEFAULT_PASSWORD=apexlegends?
      - NGINX_HOST=nginx
      - PHANTOMJS_HOST=phantomjs
      - PHANTOMJS_PORT=8910
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - DEBUG=False
    depends_on:
      - db
      - rabbitmq
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 512

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:19303:80"
    depends_on:
      - web
    volumes:
      - media_data:/usr/src/exif/media
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 512

  phantomjs:
    image: wernight/phantomjs
    container_name: sun19-etp-phantomjs
    restart: unless-stopped
    expose:
      - 8910
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"
    environment:
      - DEFAULT_USER=pontifex
      - DEFAULT_PASSWORD=apexlegends?
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 512

  rabbitmq:
    build: ./rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    expose:
      - 5672
      - 15672
    command: "rabbitmq-server"
    mem_limit: 512m
    cpus: 1.0
    pids_limit: 512

volumes:
  postgres_data:
  media_data:
