# Generated by Django 2.1.4 on 2019-03-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='filename',
            field=models.CharField(default='image', max_length=60),
        ),
    ]
