# Generated by Django 2.1.4 on 2019-03-18 22:00

from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_images_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='ifile',
            field=models.ImageField(unique=True, upload_to=front.models.upld_dir),
        ),
    ]
